version: '3'
services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=sqlite:///db.sqlite3
    depends_on:
      - registry

  registry:
    image: registry:2
    ports:
      - "5000:5000"
