all:
  children:
    jenkins_master:
      hosts:
        master:
          ansible_host: MASTER_IP  # Will be replaced with actual IP
    jenkins_slaves:
      hosts:
        slave1:
          ansible_host: SLAVE1_IP  # Will be replaced with actual IP
        slave2:
          ansible_host: SLAVE2_IP  # Will be replaced with actual IP
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/your-key.pem